### ISSUE TITLE
Contaner not getting centered

### ISSUE THREAD

**Issue by kingRayhan** [aichbauer/styled-bootstrap-components#18]
I'm using container Component from `styled-bootstrap-components`. It's make my div full width. What's the problem?

![image](https://user-images.githubusercontent.com/7611746/53294144-36ff2f80-380b-11e9-9ea6-767c95feb63c.png)

![image](https://user-images.githubusercontent.com/7611746/53294160-804f7f00-380b-11e9-9400-e71bc8884dcc.png)

**Comment by aichbauer** [comment]
@kingRayhan thanks for reaching out... I will take a look into the issue tomorrow.

**Comment by kingRayhan** [comment]
@aichbauer if possible, will you fix this bug quickly? I wanted a project with is the package.
Thanks for your effort 😄

**Comment by aichbauer** [comment]
@kingRayhan v3.0.2 is out with a fix for that isdue
