### ISSUE TITLE
TypeError: Cannot read property 'colors' of undefined

### ISSUE THREAD

**Issue by aakhan89** [aichbauer/styled-bootstrap-components#25]
TypeError: Cannot read property 'colors' of undefined

![image](https://user-images.githubusercontent.com/38126236/54199306-6b9d0780-44ea-11e9-8bd4-cbc2c0cba2f4.png)

`
import React, {Component} from 'react';

import { Button } from 'styled-button-component';
import {
  Dropdown,
  DropdownItem,
  DropdownMenu,
} from 'styled-dropdown-component';

const SimpleDropdown = (props) => (
    <Button>Hello, World!</Button>
  );

export default SimpleDropdown;
`

**Comment by aichbauer** [comment]
@aakhan89 thanks for reaching out...

I assume you are using a `styled-components` ThemeProvider with your own theme? If so you need to merge your own theme with the one that `styled-bootstrap-components` is exporting.

like

```jsx
import { theme } from 'styled-config';
const myTheme = {
  ...yourTheme,
  ...theme,
};

const App = () => (
  <ThemeProvider theme={myTheme}>
    {/* your app here */}
  </ThemeProvider>
);
 
```

If not could you please provide a codesandbox with an example that is not working?

**Comment by aakhan89** [comment]
@aichbauer 

Thank you very much for your quickly response

as required here my current Sandbox please check and advice 

https://codesandbox.io/s/y3mrmwm1rz

**Comment by aichbauer** [comment]
@aakhan89 

https://codesandbox.io/embed/zl133391mm?fontsize=14

here is how it works, I hope I could help you out.

Feel free to close this issue if you do not have any further questions...

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89
> 
> https://codesandbox.io/embed/zl133391mm?fontsize=14
> 
> here is how it works, I hope I could help you out.
> 
> Feel free to close this issue if you do not have any further questions...

@aichbauer 
Thank you for your help, really appreciated 
going to close this issue 💯

**Comment by aakhan89** [comment]
@aichbauer 

I have done it another approach, so I request to you please check this way and let me know if it's fine?

[https://codesandbox.io/s/y3mrmwm1rz](url)

Thanks in advance

**Comment by harrythedev** [comment]
@aichbauer  hey this solution doesn't work. 
![Screen Shot 2019-08-02 at 11 29 09 AM](https://user-images.githubusercontent.com/22530537/62381137-cd512300-b518-11e9-975d-9a50e9776363.png)

i combined themes from `styled-config`. why did you use this dependency?

**Comment by michaelkrukov** [comment]
@harrythedev when you use a `{...theme, ...customTheme}` - it's not a deep merge. Every not specified property on any levels except the first one will be lost. Use some deep merging functions, or copy the whole config and update it where you need it.

**Comment by michaelkrukov** [comment]
@harrythedev also, pay attention to the order of themes in your merging. Latter ones replace earlier ones.

**Comment by harrythedev** [comment]
@michaelkrukov thanks for response. but now i'm getting tons of errors from the deepmerge now.
```
import theme from 'styled-config'
import merge from 'deepmerge'
const myTheme = merge(theme, baseTheme)
```
which results 
![Screen Shot 2019-08-02 at 11 46 18 AM](https://user-images.githubusercontent.com/22530537/62382350-61bc8500-b51b-11e9-9731-6f3530629dbc.png)

**Comment by harrythedev** [comment]
first of all, i think you should've avoided dependency when building a library.

**Comment by michaelkrukov** [comment]
@harrythedev what kind of errors? Themes are just objects with configuration, the correct merge should update changed values without changing the rest. 

There is nothing wrong with having dependencies. `styled-config` is used in all 20 independent packages in this repository for configuration.  As well as `styled-base-components` this dependency is used to avoid repeated code and difficulties in packaging and versioning. I guess there is a more elegant way to organize the infrastructure, but it's ok in my opinion.
