### ISSUE TITLE
How would I fully customize theme of (styled-config)

### ISSUE THREAD

**Issue by aakhan89** [aichbauer/styled-bootstrap-components#26]
@aichbauer 

I want to customize default theme of styled-config which is provided by you, [https://github.com/aichbauer/styled-bootstrap-components/blob/master/packages/styled-config/test/fixtures/index.js](url)

codesandbox link:
[https://codesandbox.io/s/y3mrmwm1rz](url)

help wanted:
1- how can I customize can you please explain, also I am sharing codesandbox link for your ready reference 
2- If I click outside so drop down menu should be closed

**Comment by aichbauer** [comment]
@aakhan89 I should update the docs so that it makes more sense... Actually you can just overwrite every single item from our theme.

If you want to fully customize your library you could take the theme from: https://github.com/aichbauer/styled-bootstrap-components/blob/master/packages/styled-config/test/fixtures/index.js and then just start overwriting the the parts that you want and use that theme in your `<ThemeProvider theme={theme} />`.

 Or you can `import { theme } from 'styled-config'` and then start to simply just overwrite parts that you want to differ


Here we are just overwriting the colors of the primary badge... If you do not want to spread the theme in every depth you could use lodash to merge two themes...
```jsx
import { theme } from 'styled-config';

const myTheme = {
  ...theme,
  badge: {
    ...theme.badge,
    colors: {
      ...theme.badge.colors,
      primary: {
        backgroundColor: '#000',
        backgroundColorHoverFocus: '#111',
        color: '#eee',
        linkColor: '#fff',
      },
    },
  },
};
```

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89 I should update the docs so that it makes more sense... Actually you can just overwrite every single item from our theme.
> 
> If you want to fully customize your library you could take the theme from: https://github.com/aichbauer/styled-bootstrap-components/blob/master/packages/styled-config/test/fixtures/index.js and then just start overwriting the the parts that you want and use that theme in your `<ThemeProvider theme={theme} />`.
> 
> Or you can `import { theme } from 'styled-config'` and then start to simply just overwrite parts that you want to differ
> 
> Here we are just overwriting the colors of the primary badge... If you do not want to spread the theme in every depth you could use lodash to merge two themes...
> 
> ```js-jsx
> import { theme } from 'styled-config';
> 
> const myTheme = {
>   ...theme,
>   badge: {
>     ...theme.badge,
>     colors: {
>       ...theme.badge.colors,
>       primary: {
>         backgroundColor: '#000',
>         backgroundColorHoverFocus: '#111',
>         color: '#eee',
>         linkColor: '#fff',
>       },
>     },
>   },
> };
> ```
> 
> Here is your codesandbox... Feel free to close this issue if you have no further questions...
> [![Edit styled-dropdown-component](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/xp2on9x854?fontsize=14)

Yes bro, If you update the doc it would be more helpful and appreciated, but as you suggested above I got the solution, thank you for your reply.....

I have some more quires regarding drop down menu  should I close this and create new issue ? OR can I as in the same thread ?

**Comment by aakhan89** [comment]
@aichbauer 

Here is my updated CodeSanbox I want to make the dropdown like below screen shot.

So how would I control `fontSize`, `before & after` `styled-icon use in dropdown options` etcc...

![image](https://user-images.githubusercontent.com/38126236/54273033-c431da80-45a6-11e9-81b9-c77406d02b5a.png)

**Comment by aakhan89** [comment]
@aichbauer 

How can I use `border-top: 'none'` , `border-bottom: 'none'`, `font-size: '14px'` in button component `light`

also please check the above CodeSandbox link the toggle property not working

**Comment by aakhan89** [comment]
Updated

[https://codesandbox.io/s/1vp7zvww04](url)

Issues:
1- `boxShadow: 'inset 0 3px 5px rgba(0, 0, 0, .125)',` not working in button component 
2- I want to remove arrow which is showing in button
3- Want to use icons component from `styled-icon` , how can I use `**before & after**` in DropdownItem

**Comment by aichbauer** [comment]
[![Edit styled-dropdown-component](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/79mv10zx6?fontsize=14)The icons are more `react` specific questions not really `styled-bootstrap-components` related.

the toggle on this component is related to the navigation. it needs to have a `toggleCollapse` and a `expandSm` or `expandMd` or `expandLg` or `expandXl` on it... which indicates when it is visible for the user.

To remove the arrow simply remove dropdownToggle on the Button Compnent.

boxShadow is only for the color in the theme if you want to apply it create a styled compoent...

same for border use the Button Component in a new Styled

**Comment by aakhan89** [comment]
> 
> 
> Here is the codesandbox
> [![Edit styled-dropdown-component](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/79mv10zx6?fontsize=14)
> 
> The icons are more `react` specific questions not really `styled-bootstrap-components` related, but i have a solution for you.
> 
> the toggle on this component is related to the navigation. it needs to have a `toggleCollapse` and a `expandSm` or `expandMd` or `expandLg` or `expandXl` on it... which indicates when it is visible for the user.
> 
> To remove the arrow simply remove dropdownToggle on the Button Compnent.
> 
> boxShadow is only for the color in the theme if you want to apply it create a styled compoent...
> 
> same for border use the Button Component in a new Styled

Thank you very much @aichbauer really happy with your assist 

Could you please also explain, if I have two dropdown menu both are `dropdownToggleLeft`
so how can I `dropdownToggleRight` to second one and the first one will remail `dropdownToggleLeft`

and secondly if click outside so dropdown menu should b closed

**Comment by aichbauer** [comment]
That is all pretty unrelated to `styled-bootstrap-components` and most of your questions are better for a [stackoverflow question](https://stackoverflow.com).

Actually the thing you are looking for is in this PR: #23  which should get merged pretty soon. Or you can simply add `right: 0;` and `left: 0;`. 

If you want functionality for the outside click and you think this should be supported by this library, feel free to open up a new issue with a feature request and we can discuss if this should be supported. 

For right now you can either learn how to do it your self or use packages like [react-click-outside](https://www.npmjs.com/package/react-click-outside).

**Comment by aakhan89** [comment]
Can you please confirm when have `**boxShadow**` propert in **`button component`** so why wer created with styled-component ?

` button: {
    colors: {
      primary: {
        color: '#fff',
        colorOutline: '#007bff',
        colorOutlineHover: '#fff',
        backgroundColor: '#007bff',
        backgroundColorDisabled: '#007bff',
        backgroundColorHoverFocus: '#0069d9',
        backgroundColorActive: '#0062cc',
        borderColor: '#007bff',
        borderColorDisabled: '#007bff',
        borderColorActive: '#005cbf',
        borderColorHoverFocus: '#0062cc',
        **boxShadow: 'rgba(0, 123, 255, 0.5)',**
},`

**Comment by aichbauer** [comment]
I do not fully understand your question.

But if you are talking about why there is a `boxShadow` property in the theme but not actually working as `boxShadow`, then you are probably right as this is a wrong name for it as it is only `boxShadowColor`. 

If you think this is a bug or should be renamed please feel free to open a new issue and we can discuss this.
