### ISSUE TITLE
boxShadow should be boxShadowColor

### ISSUE THREAD

**Issue by aakhan89** [aichbauer/styled-bootstrap-components#27]
I think as this is a wrong name it should be `boxShadowColor`. because `boxShadow ` property in the theme but not actually working as `boxShadow`,

Thanks

**Comment by aichbauer** [comment]
@aakhan89 I am definitely with you on this issue, but right now we could only change this theme when bumping up the major version. While I am definitely not scared to do that, I think that we should investigate into more things regarding the theme, and when we found all problems (misspelling, etc.) in this theme than we can update this.

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89 I am definitely with you on this issue, but right now we could only change this theme when bumping up the major version. While I am definitely not scared to do that, I think that we should investigate into more things regarding the theme, and when we found all problems (misspelling, etc.) in this theme than we can update this.

Agreed with you, I think I should close this for now
