### ISSUE TITLE
Ability to use bootstrap classes

### ISSUE THREAD

**Issue by dachinat** [aichbauer/styled-bootstrap-components#28]
It would be nice to have a feature so that if my component is wrapped in your provider all children can use css classes like `d-flex`, `text-danger`, and so on.

Is this "sort-of" supported now?

**Comment by aichbauer** [comment]
Currently every property that gets passed to your component will actually be rendered to the DOM. wich means that you can pass something like `<Button className="your-css-classname" id="your-css-id">My Button</Button>` and this will result into <button></button> if that is what you are asking. If not please show a more detailed example of what you are trying to achieve and we can figure it out together. 

Take a look at this codesandbox:

[![Edit classNames](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6xvkn0xl43?fontsize=14)

If this is not what you are looking for then create a codesandbox with an example.

**Comment by dachinat** [comment]
@aichbauer Thanks for this lib. I really like it.
Yeah, I went through the source code.

I was thinking of something practical like:
I wanted to align two buttons in center, so I made my custom `Center` styled component with css flex properties. It would be nicer if you could support for example `Div` component and you could have `<Div className="text-danger">Something</Div>`. Just saying.

**Comment by aichbauer** [comment]
Thank you, I am glad you like it 😀

If you think about something similar to [Utility classes of Bootstrap](https://getbootstrap.com/docs/4.3/utilities/colors/). Than I definitely would love to support this. While I think we should not use `className` for them since this library currently is `props` based.

But we could definitely support something similar to `<Button text-danger>Somthing</Button>`? What do you think of that idea?

**Comment by dachinat** [comment]
@aichbauer That sounds perfect! Yes, I was thinking of utility classes, including flex and others. It would be really great.

I'm heavily busy these days (weeks), I would contribute with prs otherwise.

So handy to use bootstrap with  styled components 🎉

**Comment by michaelkrukov** [comment]
> @michaelkrukov yeah this would be nice.... maybe we can add some of the utility classes to `styled-config` and add the utilities to all components and you can activate them simply like `<NavLink pullRight />` or something like that?

@aichbauer this is probably a more appropriate place to discuss this matter. I think a better solution than creating `<Div>` component is to add a `Utility` css-helper and add it to every existing component. 

```js
const Utilities = css`
  ${(props) => props.mlAuto && css`margin-left: auto;`};
`;

// ...

NavLink = styled.a`
  ${Utilities};
  /* ... */
`;
```

The example above will fix #38

**Comment by aichbauer** [comment]
@michaelkrukov yeah that would be a good idea...

But what I meant with add the utility classes to `styled-config` was:

We should not rewrite every utility in every component... we could make something like: 

```jsx
export const Utilities = css`
  ${(props) => props.mlAuto && css`margin-left: auto;`};
`;
```

in our `styled-config` and then add it to the component like:

```jsx
import { Utilities } from 'styled-config';

const NavLink = styled.a`
  ${Utilities};
  /* ... */
`;
```

In this way we only have to write it once...

**Comment by michaelkrukov** [comment]
@aichbauer yeah, I mean Utility as a shared helper. I'm not sure if it fits `styled-config` package, but this seems logical as such helper will be essential to every lib component and to user's components, possibly, too

**Comment by michaelkrukov** [comment]
I decided to work on this issue. [Here](https://codesandbox.io/s/utilities-uoi6w) are results so far. Looks promising.
