### ISSUE TITLE
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.

### ISSUE THREAD

**Issue by aakhan89** [aichbauer/styled-bootstrap-components#29]
I wrapped a component that is by another component. Essentially a **StyledButton within a Button.**

`const StyledButton = styled(Button)`

**Below is Console log**
![image](https://user-images.githubusercontent.com/38126236/54676713-2056aa80-4b23-11e9-9f50-d9dbbf57b754.png)

**Comment by aichbauer** [comment]
@aakhan89 can you give an example code? This is a warning from `react` itself. As I understand you do something like this:

```jsx
<Button>
  <Button>text</Button>
</Button>
```

which is not good. Because valid html does not support buttons within buttons... so what you want is most likely to be something like:

```jsx
<div>
  <Button>text</Button>
</div>
```

**Comment by aakhan89** [comment]
@aichbauer 

There isn't buttons withing buttons check me DOM of react dev tool, also I am going to share live example in codesandBox

![image](https://user-images.githubusercontent.com/38126236/54677459-c0610380-4b24-11e9-98a2-6e25eb3b10f6.png)


It seem I am using I am wrapping const StyledButton = styled(Button) so it could be issue... but I am not sure....

**Comment by aichbauer** [comment]
@aakhan89 can you give me an codesandbox example...

**Comment by aakhan89** [comment]
@aichbauer 

https://codesandbox.io/s/1vp7zvww04

**Comment by aichbauer** [comment]
I can't see any problems in the console... are you sure this is the example to reproduce?

**Comment by aakhan89** [comment]
Actually when I am trying to show dynamic content as you can see on CodeSandBox **`{this.props.publishedStatus}`** then I am facing these warnings, If I place simple text so there is no warnings

**Comment by aichbauer** [comment]
and what is `this.props.publishedStatus`? You need to give me more information, or something to recreate, otherwise I can not help you...

**Comment by aakhan89** [comment]
> 
> 
> and what is `this.props.publishedStatus`? You need to give me more information, or something to recreate, otherwise I can not help you...

@aichbauer Issue has been resolved, the issue wasn't related with **`const StyledButton = styled(Button)`** I am going to close this with apologize

**Comment by exlnt** [comment]
@aakhan89 Can you please post the root cause of your issue? I am running into the same error and I cannot find nested buttons anywhere in my code.

**Comment by VityaSchel** [comment]
I used material UI's React Button inside my html button to have ripple effect :D 
Is it a hack or bad practice?

**Comment by saifur281** [comment]
Hi the same problem appear to me as well. but i solved it . in my case when i use 2 buttons under CardedActionArea ( from "@material-ui/core ) . that time got the error .. if you having the same problem.. just a simple thing replace the CardActionArea to a div tag.. hope that will solve the problem .. Thanks

**Comment by volevol** [comment]
This causes the problem:
```
<CardActionArea>
  <CardActions>
    <Button>click me</Button>
  </CardActions>
</CardActionArea>
```

This do not:
```
<CardActionArea>
  *another content*
</CardActionArea>
<CardActions>
  <Button>click me</Button>
</CardActions>
```

`CardActions` is like a button, `Button` is button. Button inside button causes such an error. You need to separate these two components.

[example of working CardActions with Button](https://codesandbox.io/s/iuqwtd?file=/demo.js:978-1116)

**Comment by raneem13j** [comment]
I have the same problem  even if I use div tag it keeps giving me the same error, this is my code, when click on edit icon a form component pop up :


```
<div className="ccclients_container">
        <div className="cchead_container">
          <h1 className="ccheadline1 ccinside">OUR</h1>
          <h1 className="ccheadline2 ccinside">CLIENTS</h1>
        </div>
        <div className="ccsection ccsection_clients">
          {Object.keys(categories).map((category_name,) => (
            <>
              <div className="cccard">
                <div className="cccategory">
                  <h2 className="cccategory_h">{category_name}</h2>
                </div>
                <div className="ccclients_card">
                  {categories[category_name].map(
                    ({ client_name, client_city, index }, i) => (
                      <ul className="ul" key={data[i]._id}>
                        <li className="li-cc">
                          {client_name}-
                          <span className="span-cc">{client_city}</span>
                        </li>
                        <div>
                        <button
                          id="myBtn"
                          className="btn"
                          onClick={() => handleEdit(data[i]._id)}
                        >
                          {showEditForm && (
                            <ClientsEditForm
                              id={currentId}
                              onClose={handleCloseClick}
                            />
                          )}
                          <img src={edit} alt="" className="edit" />
                        </button>
                        </div>
                        <div>
                        <button
                          className="btn"
                          onClick={() => handleDelete(data[i]._id)}
                        >
                          <img src={delet} alt="" className="edit" />
                        </button>
                        </div>
                      </ul>
                    )
                  )}
                  <img src={add} alt="" className="edit" />
                </div>
                <div></div>
              </div>
            </>
          ))}
        </div>
      </div>

```
