### ISSUE TITLE
Components should not rely on react-router-dom

### ISSUE THREAD

**Issue by chetmurphy** [aichbauer/styled-bootstrap-components#3]
My project uses router5 with mobx, so this dependency means that styled-bootstrap-components is not compatible without rewriting the NavLink component.

**Comment by aichbauer** [comment]
Hey, thanks for your interest in this project.

So do you think we should only use the plain a tag? How would you use the NavLink in combination with any router?

**Comment by chetmurphy** [comment]
For router5 I simply call a handler provided by the router store.

Note: This is also how React Semantic UI does it.

const rightItems: MenuItemProps[] = [
  { as: 'a', content: 'Login', key: 'login', routename: 'signin', onClick: link },
  { as: 'a', content: 'Register', key: 'register', routename: 'signup', onClick: link }
];


--Chet

________________________________

**Comment by aichbauer** [comment]
I will take a look into it as soon as possible.

Also, Pull Requests are always welcome. If you already have solution that fits all needs, feel free to open a PR.

**Comment by chetmurphy** [comment]
Thanks. My current solution is to just remove the router prop, but that is not a generic solution. The react-router Link class is just a React.Component<LinkProps,any> class so it seems like it would be possible to pass that class to your library rather than have it built-in

I am currently focused on seeing what it would take to use typescript with your library starting with styled-system which also does not types defined.

________________________________

**Comment by aichbauer** [comment]
So I had time last night to play around with it. I do not know why I didn't came up with it in first place. But yeah its simple as

```jsx
import { Link } from 'react-router-dom';
import { NavLink } from 'styled-nav-component';

const myComponent = (props) => (
  <div>
    {/* both of these work */}
    <NavLink><Link to="#"></Link></NavLink>
    <Link to="#"><NavLink></NavLink></Link>
  </div>
);
```

So we can get rid of it. I try do get it done as soon as possible. Maybe you have an more detailed example on how to use it with router5, then we could add this to the docs?

**Comment by chetmurphy** [comment]
Good.

FYI: I’m still in the process of converting your components and styled-system to typescript, so it is going to take a few more days until I have a working example.

________________________________
