### ISSUE TITLE
Dropdownmenu Right Alignment

### ISSUE THREAD

**Issue by aakhan89** [aichbauer/styled-bootstrap-components#30]
@aichbauer 

Hi,
Can you please share regarding Dropdownmenu Right Alignment

Just wanted to ask have you merged 
https://github.com/aichbauer/styled-bootstrap-components/pull/23

**Comment by aichbauer** [comment]
I do not really understand your question... Can you clarify?

If you asked if is merged, then no... we need to add documentation for that feature before we can merge it.

**Comment by aakhan89** [comment]
I was asking about merged
