### ISSUE TITLE
1 Dropdown Menu should be open at one time

### ISSUE THREAD

**Issue by aakhan89** [aichbauer/styled-bootstrap-components#31]
I have 3 drop down menu when I click on all the drop down menu remain open however when I click another one so previous one should b close.

Last toggle option has an issue with close and open

https://codesandbox.io/s/1vp7zvww04

**Comment by aichbauer** [comment]
That is not really a issue with `styled-bootstrap-components`. You need to set the `boolean` for the other dropdown to `false`

a quick and dirty fix would be:

```js
 handleOpenCloseDropdown(dropdownHidden) {
    this.setState({
      published: false,
      text1: false,
      text2: false,
      [dropdownHidden]: true,
    });
  }
```
