### ISSUE TITLE
<Column> lacks features from bootstrap's .col

### ISSUE THREAD

**Issue by michaelkrukov** [aichbauer/styled-bootstrap-components#33]
Currently `styled-grid-system-component` is taking sizes from smallest to largest and by default it's 100%. It's behavior is quite different from bootstrap's `.col`. 

* [`styled-grid-system-component` behavior](https://codesandbox.io/embed/2zy901405n)
* [`bootstrap` behavior](https://codesandbox.io/embed/zzq8l9p9x3)

I think `Columns` should take their sizes from largest (starting from size corresponding to current screen size) to smallest. Also, `Column`s should try to distribute available space evenly if no sizes specified.

**Comment by michaelkrukov** [comment]
[CodeSandbox with `Column`](https://codesandbox.io/embed/oxqrjv44o9) (code taken from #34)

**Comment by aichbauer** [comment]
@michaelkrukov thank you for your contribution. You are right. I will take a look into #34 as soon as possible.
