### ISSUE TITLE
<Modal> lacks features from bootstrap's .modal

### ISSUE THREAD

**Issue by michaelkrukov** [aichbauer/styled-bootstrap-components#35]
Currently `Modal` from `styled-modal-component` lacks features I expected from the modal component:

- Backdrop with the ability to close the visible modal dialog by clicking outside of the dialog;
- Preventing the body from scrolling while the dialog is open;
- Animations for appearing and disappearing;

I created a version of Modal with needed features using some relatively straightforward approaches. It supports tall content that can be scrolled, only requires one component and mostly based on code from `styled-modal-component`.

[Enhanced `Modal`](https://codesandbox.io/s/93x8xql2y4?fontsize=14)

I think it would be nice to simplify current Modal's API to one component and add features from `bootstrap`. It's also possible to take inspiration from [reactstrap's modal](https://reactstrap.github.io/components/modals/). For example, add a prop to hide backdrop or add `returnFocusAfterClose` prop.

This component can be integrated instead of current `Modal` almost without loss of possible use cases but with the change to API (encapsulation of `ModalDialog` and `ModalContent`).

**Comment by aichbauer** [comment]
@michaelkrukov I really like the idea behind it, and love to implement it. Could you bring in a PR? Thanks again for your contributions, I appreciate them.

**Comment by aichbauer** [comment]
@michaelkrukov thank you for your contribution. On the first look it looks good to me. I will try to make a review of the PR within this week.

**Comment by michaelkrukov** [comment]
@aichbauer alright :ok_hand:
