### ISSUE TITLE
How to use 'navbar-nav' and 'pull-right' functionality?

### ISSUE THREAD

**Issue by zhangriyueming** [aichbauer/styled-bootstrap-components#38]
How to use 'navbar-nav' and 'pull-right' functionality?

**Comment by aichbauer** [comment]
Could you give us a bit more information what you are trying to do...

I guess the documentation should help you: [nav end](https://aichbauer.github.io/styled-bootstrap-components/?path=/story/navs--horizontal-end)

**Comment by zhangriyueming** [comment]
@aichbauer , Check `navbar-nav` and `pull-right` style in bootstrap. And how to archive `<div class="nav navbar-nav pull-right"></div>` with styled-bootstrap-components?

**Comment by michaelkrukov** [comment]
@zhangriyueming looks like `pull-right` is not an easy utility class to find. I suppose you want to use `margin: auto` for aligning individual items. Like [that](https://codesandbox.io/s/great-knuth-uw53g) for example.

**Comment by aichbauer** [comment]
Currently this lib does not support utility classes, but we are open for any suggestions an help... We already started in discussing this issue in #28 

Maybe we can discuss this there...

**Comment by michaelkrukov** [comment]
@aichbauer while there are no utility classes, it may be practical to add `right` prop to `<NavLink>`. This [looks](https://codesandbox.io/s/clever-oskar-flb1m) nice

**Comment by aichbauer** [comment]
@michaelkrukov yeah this would be nice.... maybe we can add some of the utility classes to `styled-config` and add the utilities to all components and you can activate them simply like `<NavLink pullRight />` or something like that?

**Comment by zhangriyueming** [comment]
@aichbauer @michaelkrukov , How about have a 'common component' to have all utilities features, and then let all of components in the library extends from it?
