### ISSUE TITLE
<Column> Lacks 'offset' feature

### ISSUE THREAD

**Issue by zhangriyueming** [aichbauer/styled-bootstrap-components#40]
<Column> should support `offset` like:

`<Column mdOffset={x} md={x} sm={x} smOffset={x}>`

**Comment by aichbauer** [comment]
This could be a way to do it. @michaelkrukov what do you think about this?

Currently you could simulate any offset with new  self closing `<Colum />`

something like:

```jsx
const MyComponent = props => (
  <>
    <Column md={x} />
    <Column md={x}>Content</Column>
  </>
);
```

**Comment by michaelkrukov** [comment]
Actually, adding offset is pretty straightforward. If I'm not missing anything, it's a matter of adding a new function and updating media in `<Column>`.

```js
// ...

export const columnStyleForOffset = offset => css`
  margin-left: ${percentage(offset / colums)};
`;

// ...
```

```js
// ...

@media (min-width: ${props => props.theme.screenSize.md}) {
  ${props => props.md && columnStyleForSize(props.md)}
  ${props => props.mdOffset && columnStyleForOffset(props.mdOffset)}
}

// ...
```

```js
<Column md={3} mdOffset={3}>2</Column>
```

**Comment by michaelkrukov** [comment]
@aichbauer I can make a pr with offset feature for columns

**Comment by aichbauer** [comment]
@michaelkrukov that would be great 👍
