### ISSUE TITLE
Want to hide alert form modal

### ISSUE THREAD

**Issue by aakhan89** [aichbauer/styled-bootstrap-components#50]
Want to hide modal alert onClick kindly see the screen shot also CodeSandbox link

![image](https://user-images.githubusercontent.com/38126236/59563127-31925300-904f-11e9-8eb2-0d6ce2e2c586.png)

https://codesandbox.io/s/modal-with-alert-7g174

**Comment by aakhan89** [comment]
Want to set width 600px instead of 500px

however below mentioned classes width is differnt
`sm only on Modal Type: boolean
lg only on Modal Type: boolean`

**Comment by michaelkrukov** [comment]
First of all, don't create issues with multiple questions. 

Regarding hiding - use property `hidden`, not `hiddenAlert`; pass state value `hiddenAlert`, not `hiddenAlert`; initially you want to set `hiddenAlert` to `false`.

You can customize components from modal using functionality added in #43. Check out modal's [readme](https://github.com/aichbauer/styled-bootstrap-components/tree/master/packages/styled-modal-component#properties) for details. You can pass any style or component for customization.

**Comment by aakhan89** [comment]
I tried DismissAlert from StroyBook but not working also I updated my CodeSandbox, you are requested to please have a look thank you @michaelkrukov

**Comment by aakhan89** [comment]
Can you please upload examples on StoryBook how to customize components from modal using functionality added in #43. also how can pass any style or component for customization.

**Comment by michaelkrukov** [comment]
@aakhan89 you didn't fix all the issues your code has. 

> use property `hidden`, not `hiddenAlert`; pass state value `hiddenAlert`, not `hiddenAlert`; initially, you want to set `hiddenAlert` to false. 

Use `hiddenAlert` for alert's hidden, not `hidden`. Your `hidden` is for modal.

**Comment by michaelkrukov** [comment]
@aakhan89 the storybook is updated with the example for customization. But it's not published to the website yet. You can watch examples in the repository or run the storybook by yourself.

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89 the storybook is updated with the example for customization. But it's not published to the website yet. You can watch examples in the repository or run the storybook by yourself.

@michaelkrukov Thanks for your reply, I will check examples in the repository :)

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89 you didn't fix all the issues your code has.
> 
> > use property `hidden`, not `hiddenAlert`; pass state value `hiddenAlert`, not `hiddenAlert`; initially, you want to set `hiddenAlert` to false.
> 
> Use `hiddenAlert` for alert's hidden, not `hidden`. Your `hidden` is for modal.

@michaelkrukov I am sorry, I tried it, but I am not sure what I am doing wrong, It would be highly appreciated if you can fix on the same CodeSandBox ?

**Comment by michaelkrukov** [comment]
@aakhan89 https://codesandbox.io/s/modal-with-alert-rgjbm

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89 https://codesandbox.io/s/modal-with-alert-rgjbm

@michaelkrukov Thanks alot bro :)

**Comment by aakhan89** [comment]
@michaelkrukov 

Just wanted to ask why we are using `onKeyPress={() => this.toggleAlert()}` however we have  `onClick={() => this.toggleAlert()}`

**Comment by michaelkrukov** [comment]
@aakhan89 I only fixed problems that were in the sandbox. It's not needed.
