### ISSUE TITLE
ModalDialog  max-width

### ISSUE THREAD

**Issue by aakhan89** [aichbauer/styled-bootstrap-components#53]
How can I modify  ModalDialog `max-width: 500px;` to `max-width: 600px;`

**Comment by michaelkrukov** [comment]
In the new version of modal, you can use 'dialogProps'. Example: https://codesandbox.io/s/modal-with-alert-rgjbm?fontsize=14

**Comment by aakhan89** [comment]
@michaelkrukov and how about in earlier version ?

**Comment by michaelkrukov** [comment]
@aakhan89 I'm not sure, I think your best option is to temporary copy new `styled-modal-component` and use it until new version's release

**Comment by aichbauer** [comment]
@aakhan89 

use could use the style prop

```js
<ModalDialog style={{ maxWidth: "600px" }}>
  ...
</ModalDialog>
```

[![Edit Modal max-with](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modal-with-styled-dialog-6f2o3?fontsize=14)
```

here is an example
[![Edit Modal max-with](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modal-with-styled-dialog-6f2o3?fontsize=14)

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89
> 
> use could use the style prop
> 
> ```js
> <ModalDialog style={{ maxWidth: "600px" }}>
>   ...
> </ModalDialog>
> ```
> 
> [![Edit Modal max-with](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/modal-with-styled-dialog-6f2o3?fontsize=14)
> 
> ```
> 
> here is an example
> [![Edit Modal max-with](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modal-with-styled-dialog-6f2o3?fontsize=14)
> ```

@aichbauer 

what's wrong with this body ? can you please find out ?
![image](https://user-images.githubusercontent.com/38126236/60765165-5e1a1780-a0af-11e9-8445-15731b7fbfed.png)

**Comment by aakhan89** [comment]
for the time being I have changed in the node_modules `500px to 600px`, but I don't know what's the issue with this

**Comment by aichbauer** [comment]
@aakhan89 what version do you use?

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89 what version do you use?

`"styled-bootstrap-components": "^3.0.2",`
` "styled-components": "^4.1.3",`

**Comment by aichbauer** [comment]
@aakhan89  You can try to overwrite  with `max-width: 600px !important;`
