### ISSUE TITLE
multiSelect, singleSelect Form fields

### ISSUE THREAD

**Issue by aakhan89** [aichbauer/styled-bootstrap-components#58]
@aichbauer @michaelkrukov 
can you please add multiSelect, singleSelect, createable multiSelect, createable singleSelect Component in the Form section?

**Comment by michaelkrukov** [comment]
@aakhan89, doesn't components with this functionality already exists? https://aichbauer.github.io/styled-bootstrap-components/?path=/story/forms--form-controls

Please, be more specific and refer to examples if possible.

**Comment by aichbauer** [comment]
@aakhan89 any updates on this one? Did the info from @michaelkrukov help you?

**Comment by aakhan89** [comment]
@michaelkrukov @aichbauer 

Actually I achieved by [https://react-select.com/home](url), so you can close this or you may also see examples for your ready reference
