### ISSUE TITLE
Fix: NavLink using with a router component

### ISSUE THREAD

**Issue by aichbauer** [aichbauer/styled-bootstrap-components#6]
When using a router (in my case react-router-dom) with the NavBarLink component. I got a error warning from react. because we are nesting a-tags within a-tags which is not valid.

`Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.`

so we could add a new prop on Navlinks e.g. `span` and then use the styling from NavLink on a span instead of an a-tag, only when we apply this property. And if we do not use this property we should use a normal a-tag instead.

**Comment by michaelkrukov** [comment]
You can replace tag using ["as" polymorphic prop](https://www.styled-components.com/docs/api#as-polymorphic-prop) from styled-components.

Example:

```js
import { Link } from 'react-router-dom';

export default () => (
  <Navbar>
    <NavbarLink as={Link} to="/">hello there</NavbarLink>
  </Navbar>
);
```

**Comment by aichbauer** [comment]
@michaelkrukov that sounds exactly like the solution to this kind of problem.

Would you be interested to contribute a Pull Request?

**Comment by michaelkrukov** [comment]
@aichbauer it's part of `styled-components` and it doesn't require any changes in `styled-bootstrap-components`

**Comment by aichbauer** [comment]
@michaelkrukov great 😀 I will add an working codesandbox example to this issue and close the issue

**Comment by aichbauer** [comment]
@michaelkrukov thanks again...

here is a working codesandbox example:

[![Edit NavbarLink as RouterLink](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mq26579yjy?fontsize=14)
