### ISSUE TITLE
how to apply custom css to styled-navbar-component

### ISSUE THREAD

**Issue by farazbhinder** [aichbauer/styled-bootstrap-components#66]
Hi,
I want to change the background color of the navbar. I write inline style like following: 
```<Navbar expandLg style={{ backgroundColor: "red" }}>```  
But this doesn't makes it take the new background-color, and when I open developer tools from Firefox and uncheck the navbar's applied rule, i.e., ```background-color: #f0f0f0 !important;```, my style is applied. Is it possible to give custom backgound-color to the Navbar? Thanks, Merry Christmas and Happy new year :)

**Comment by farazbhinder** [comment]
Whoops, after searching a bit more I found a workaround at:  
https://joshtronic.com/2018/03/22/how-to-important-inline-styles-in-react/

I need to apply the style to the Navbar using ref like following:
```
ref = {
    el => {
        if (el) {
            el.style.setProperty("background-color", "red", "important")
        }
    }
}
```

**Comment by michaelkrukov** [comment]
Well, when you use `!important` it will take precedence over similar rules. That's how it supposed to work. 

Use `styled-components` for styling and be careful about your rules' specifity (Google it, if you not sure) . Your current solution is pretty bad, you shouldnt use it. 

You can check `styled-components` docs for more information about specifity issues. [Link](https://www.styled-components.com/docs/advanced#issues-with-specificity)
