### ISSUE TITLE
Error trying to build packages.

### ISSUE THREAD

**Issue by apisandipas** [aichbauer/styled-bootstrap-components#71]
Hello, I'm vetting this package for my place of employment as we've bought in the styled-components and out current integration with Bootstrap is clunky. I'm trying to build the packages locally so that I might toy around in Storybook locally. However I'm getting an error:

lerna ERR! prepublish Errored while running script in 'styled-base-components'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run prepublish
lerna ERR! SyntaxError: src/components/transitions.js: Unexpected token (182:6)
lerna ERR!   180 |       noInitialEnter,
lerna ERR!   181 |       hideOnExit,
lerna ERR! > 182 |       ...transitionProps
lerna ERR!       |       ^
lerna ERR!   183 |     } = this.props;
lerna ERR!   184 | 
lerna ERR!   185 |     const { status } = this.state;
lerna ERR! error Command failed with exit code 1.
lerna ERR! yarn run v1.21.1
lerna ERR! $ babel --root-mode upward src --out-dir lib
lerna ERR! src/components/globalStyle.js -> lib/components/globalStyle.js
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at /Users/bryan/Code/styled-bootstrap-components/node_modules/execa/index.js:236:11

I get this when I run `lerna run prepublish` (which may be my mistake, but it seemed to be the way to get all the packages to build. Perhaps there is a better way that just isnt documented ?) The above to me appears to be a babel issue as it's choking on the spread operator. It would appear to me you're property configured to deal with the spread operator, so I'm short on guesses here.

**Comment by michaelkrukov** [comment]
```
SyntaxError: src/components/transitions.js: Unexpected token (182:6)
```

Well. did you change anything here?

**Comment by aichbauer** [comment]
@apisandipas I think what you try to accomplish is not going to work with `lerna prepublish`

first thing after cloning this repo:

```sh
# get into the directory where this project is cloned
$ cd styled-bootstrap-components
# install all local dependencies
$ yarn
# boostrap all lerna packages (install dependencies of packages etc...)
$ lerna boostrap
# cd into storybook
$ cd .storybook
# install storybook dependencies
$ yarn
# start storybook in dev mode
$ npm run storybook
```

**Comment by apisandipas** [comment]
Thanks Guys . This can be closed now as my dev environment is working properly.
